name: 'Build Kernel'
description: 'Build the Linux kernel'
inputs:
  kernel-version:
    description: 'Kernel branch or tag name to checkout'
    required: true
  os:
    description: 'Build machine OS'
    required: true
  arch:
    description: 'Architecture to build'
    required: true
  ack:
    description: 'Whether to build the Android Common Kernel'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout kernel version
      shell: bash
      env:
        ACK: ${{ inputs.ack }}
        ARCH: ${{ inputs.arch }}
        VERSION: ${{ inputs.kernel-version }}
      run: make linux_download

    - name: Install common dependencies
      shell: bash
      run: |
        sudo apt update && sudo apt install -y \
          build-essential \
          bc \
          bison \
          flex \
          libelf-dev \
          libssl-dev \
          ncurses-dev \
          llvm \
          clang-tools \
          lld \
          lz4 \
          xz-utils

    - name: Install pahole
      if: ${{ inputs.os == 'ubuntu-22.04' }}
      shell: bash
      run: sudo apt install pahole

    - name: Install pahole
      if: ${{ inputs.os == 'ubuntu-20.04' }}
      shell: bash
      run: sudo apt install dwarves

    - name: Install x86_64 dependencies
      if: ${{ inputs.arch == 'x86_64' }}
      shell: bash
      run: sudo apt update && sudo apt install -y qemu-system-x86

    - name: Install arm64 dependencies
      if: ${{ inputs.arch == 'arm64' }}
      shell: bash
      run: |
        sudo apt update && sudo apt install -y \
          binutils-aarch64-linux-gnu \
          gcc-aarch64-linux-gnu

    - name: Set Linux source directory
      if: ${{ inputs.ack == 0 }}
      shell: bash
      run: echo "LINUX_SRC=linux-${{ inputs.kernel-version }}" >> $GITHUB_ENV

    - name: Set ACK source directory
      if: ${{ inputs.ack == 1 }}
      shell: bash
      run: echo "LINUX_SRC=${{ inputs.kernel-version }}" >> $GITHUB_ENV

    - name: Build kernel
      shell: bash
      env:
        ACK: ${{ inputs.ack }}
        ARCH: ${{ inputs.arch }}
      run: |
        make -j$(nproc) linux
