name: Build and Test All
on:
  push:
    branches:
      - main
    path:
      - '*'
      - '!**/*.md'
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        kernel: [{ack: 0, version: 5.10.y}, {ack: 0, version: 5.15.y}, {ack: 0, version: 6.1.y}, {ack: 0, version: 6.6.y}, {ack: 1, version: android13-5.10-lts}, {ack: 1, version: android14-5.15-lts}]
        arch: [arm64, x86_64]
    with:
      host-os: ubuntu-20.04
      ack: ${{ matrix.kernel.ack }}
      arch: ${{ matrix.arch }}
      version: ${{ matrix.kernel.version }}

  rootfs:
    uses: ./.github/workflows/rootfs.yml
    strategy:
      matrix:
        arch: [arm64, x86_64]
    with:
      host-os: ubuntu-22.04
      arch: ${{ matrix.arch }}

  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    needs: rootfs
    strategy:
      matrix:
        kernel: [{ack: 0, version: 5.10.y}, {ack: 0, version: 5.15.y}, {ack: 0, version: 6.1.y}, {ack: 0, version: 6.6.y}, {ack: 1, version: android13-5.10-lts}, {ack: 1, version: android14-5.15-lts}]
        arch: [arm64, x86_64]
    with:
      host-os: ubuntu-22.04
      ack: ${{ matrix.kernel.ack }}
      arch: ${{ matrix.arch }}
      version: ${{ matrix.kernel.version }}
