name: Build And Test
on:
  workflow_dispatch:
    inputs:
      host-os:
        required: false
        type: choice
        options:
          - ubuntu-22.04
          - ubuntu-20.04
        default: ubuntu-22.04
      ack:
        required: true
        type: choice
        options:
          - '0'
          - '1'
      arch:
        required: true
        type: choice
        options:
          - x86_64
          - arm64
      version:
        required: true
        type: string
      use-cached:
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      host-os:
        required: false
        type: string
        default: ubuntu-22.04
      ack:
        required: true
        type: string
      arch:
        required: true
        type: string
      version:
        required: true
        type: string
      use-cached:
        required: false
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      host-os: ${{ inputs.host-os }}
      ack: ${{ inputs.ack }}
      arch: ${{ inputs.arch }}
      version: ${{ inputs.version }}
      use-cached: ${{ inputs.use-cached }}

  test:
    uses: ./.github/workflows/test.yml
    needs: build
    with:
      ack: ${{ inputs.ack }}
      arch: ${{ inputs.arch }}
      version: ${{ inputs.version }}
      artifact-dir: ${{ needs.build.outputs.artifact-dir }}
      kernel-image-name: ${{ needs.build.outputs.kernel-image-name }}
      suffix: ${{ needs.build.outputs.suffix }}
